### ISSUE TITLE
Can not find image capture functionality in new update.

### ISSUE THREAD

**Issue by npvaddoriya** [aiyaapp/AiyaEffectsAndroid#43]
@aiyaapp Thanks for a great update.
I have updated your SDK and now i m only getting video recording, But i also want to capture image like you are giving in older version of SDK.

**Comment by WangYng** [comment]
We will soon add this functionality

**Comment by ruanrongding** [comment]
Thank you very much for your feedback, the current version does not provide photo capabilities, the next version we will add to, thank you.

**Comment by npvaddoriya** [comment]
Thanks for your help and support 😃.  We are eagerly waiting for your
update.

**Comment by ruanrongding** [comment]
We have updated the photo click, long press the record function

**Comment by npvaddoriya** [comment]
Thanks a lot..😊

**Comment by npvaddoriya** [comment]
@aiyaapp 
Is there any way to zoomIn/zoomOut Camera,If so can you please provide explanation for same?
Thanks.

**Comment by simformsolutions** [comment]
@WangYng  does this sdk support Oreo OS?, and also we need access of your camera so we want to customise , can you please help us in that.

**Comment by ruanrongding** [comment]
You can download the project on github https://github.com/aiyaapp/AAVT, where aavt is the camera's custom function source code
, You can customize the camera by modifying the parameters of the MediaConfig class plane. Import aavt as a module into your project
