### ISSUE TITLE
Phone Permission 

### ISSUE THREAD

**Issue by jays95jp** [aiyaapp/AiyaEffectsAndroid#52]
@aiyaapp @ruanrongding @doggycoder  First of all great job, I appreciate your work. 👍  I have one question. If i am not give READ_PHONE_STATE permission than is it ok?. Is it commissary to give that permission ?
And again Thanks for this library.

**Comment by jays95jp** [comment]
@aiyaapp  Please give update on this. Your

**Comment by jays95jp** [comment]
@aiyaapp  Please update on this. Why we need phone Call permission. If i am not giving that permission than get crash.

**Comment by ruanrongding** [comment]
To obtain the IMEI information of the mobile phone when it is certified, it is necessary to open the READ_PHONE_STATE permission, all of which need the phone permission.@jays95jp
