### ISSUE TITLE
华为mate9 安卓8.0报错

### ISSUE THREAD

**Issue by 385841539** [aiyaapp/AiyaEffectsAndroid#55]
安装报错 
03-15 21:15:47.961 16493-16493/com.zhang.camerademo E/Minikin: Could not get cmap table size!
03-15 21:15:48.036 16493-16493/com.zhang.camerademo E/CrashReport: --------------------------------------------------------------------------------------------
03-15 21:15:48.036 16493-16493/com.zhang.camerademo E/CrashReport: --------------------------------------------------------------------------------------------
03-15 21:15:48.194 16493-16493/com.zhang.camerademo E/CrashReport: UserInfo is disable
03-15 21:15:48.289 16493-16524/com.zhang.camerademo E/vndksupport: Could not load vendor/lib64/egl/libGLES_mali_v2.so from sphal namespace: dlopen failed: library "vendor/lib64/egl/libGLES_mali_v2.so" not found.
03-15 21:16:27.963 16493-16493/com.zhang.camerademo E/CrashReport: UserInfo is disable

------------------

                                                                      Process: com.zhang.camerademo, PID: 16493
                                                                      java.lang.NullPointerException: Attempt to read from null array
                                                                          at com.aiyaapp.camera.sdk.etest.AppOsUtils.getTotalCpuTime(AppOsUtils.java:46)
                                                                          at com.aiyaapp.camera.sdk.etest.AppOsUtils.getProcessCpuRate(AppOsUtils.java:23)
                                                                          at com.aiyaapp.camera.sdk.etest.EDataShow.run(EDataShow.java:90)
                                                                          at java.lang.Thread.run(Thread.java:784)

**Comment by WangYng** [comment]
你使用的是哪个Demo?

**Comment by WangYng** [comment]
你使用的是哪个Demo?

**Comment by itcmixu** [comment]
楼主解决了没有？我也是Mate9，想使用opencv manager 共享库，怎么都不能成功。

错误信息如下：
E/vndksupport: Could not load vendor/lib64/egl/libGLES_mali_v2.so from sphal namespace: dlopen failed: library "vendor/lib64/egl/libGLES_mali_v2.so" not found.

**Comment by itcmixu** [comment]
我知道问题原因了，但怎么解决的方法还没找到。

问题原因是： mate9最近把系统升级为8.0版了，8.0版VNDK的使用方法有了变化，所以会报错：E/vndksupport: Could not load vendor/lib64/egl/libGLES_mali_v2.so from sphal namespace: dlopen failed: library "vendor/lib64/egl/libGLES_mali_v2.so" not found.

问题原理在这里，我正在看：https://source.android.com/devices/architecture/vndk/。暂时还不知道解决方法。

我刚刚在Lenovo PB2-690N(安卓6.0.1版)上回避了上述问题。

**Comment by aiyaapp** [comment]
@itcmixu 感谢，是因为vndk的问题，不过我看这个错误似乎不影响正常使用。
