### ISSUE TITLE
oppo arm64-v8a架构崩溃

### ISSUE THREAD

**Issue by suzfsir** [aiyaapp/AiyaEffectsAndroid#62]
在bugly上收集到了很多崩溃的日志，基本都是oppo类型，cpu为arm64-v8a，这个是什么情况？
1 #00 pc 0003b4a4 /system/lib/libc.so (tgkill+12) [armeabi-v7a]
--
2 #01 pc 00017a01 /system/lib/libc.so (pthread_kill+52) [armeabi-v7a]
3 #02 pc 00018667 /system/lib/libc.so (raise+10) [armeabi-v7a]
4 #03 pc 00014e27 /system/lib/libc.so (__libc_android_abort+34) [armeabi-v7a]
5 #04 pc 0001321c /system/lib/libc.so (abort+4) [armeabi-v7a]
6 #05 pc 0003bb49 /data/app/lib/arm/libAyCoreSdk.so (__gnu_cxx::__verbose_terminate_handler()+224) [armeabi-v5te]
7 #06 pc 00023fe3 /data/app/lib/arm/libAyCoreSdk.so (__cxxabiv1::__terminate(void (*)())+2) [armeabi-v5te]
8 #07 pc 00024013 /data/app/lib/arm/libAyCoreSdk.so (std::terminate()+10) [armeabi-v5te]
9 #08 pc 00023cff /data/app/lib/arm/libAyCoreSdk.so (__cxa_throw+110) [armeabi-v5te]
10 #09 pc 000394df /data/app/lib/arm/libAyCoreSdk.so [armeabi-v5te]
11 #10 pc 00039e85 /data/app/lib/arm/libAyCoreSdk.so [armeabi-v5te]
12 #11 pc 00039ebb /data/app//lib/arm/libAyCoreSdk.so [armeabi-v5te]
13 #12 pc 0000e448 /data/app/lib/arm/libAyCoreSdk.so (GetLicenseInfo(rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>, rapidjson::CrtAllocator>&, LicenseInfo&)+796) [armeabi-v5te]
14 #13 pc 00020f04 /data/app/lib/arm/libAyCoreSdk.so (Statistics::ifNeedCheckLicense()+84) [armeabi-v5te]
15 #14 pc 000212dc /data/app/lib/arm/libAyCoreSdk.so (Statistics::authentication()+84) [armeabi-v5te]
16 #15 pc 00022da8 /data/app/lib/arm/libAyCoreSdk.so (Statistics::threadLoop(void*)+128) [armeabi-v5te]
17 #16 pc 0001718f /system/lib/libc.so (__pthread_start(void*)+30) [armeabi-v7a]
18 #17 pc 0001517f /system/lib/libc.so (__start_thread+6) [armeabi-v7a]

**Comment by WangYng** [comment]
已经在QQ群反馈, 问题已经解决

**Comment by ustcJianglong** [comment]
怎么修复的

**Comment by penglu20** [comment]
求问一下，这是怎么解决的？
我也遇到了类似的
